export const ENTER_WORD_REQUEST = 'ENTER_WORD_REQUEST'
export const ENTER_WORD_SUCCESS = 'ENTER_WORD_SUCCESS'
export const ENTER_WORD_FAIL = 'ENTER_WORD_FAIL'

export const ADD_NEW_WORD_REQUEST = 'ADD_NEW_WORD_REQUEST'
export const ADD_NEW_WORD_SUCCESS = 'ADD_NEW_WORD_SUCCESS'
export const ADD_NEW_WORD_FAIL = 'ADD_NEW_WORD_FAIL'
